export const USER_UPDATE = 'USER_UPDATE'
export const USER_RESET = 'USER_RESET'

export const COLLECTION_UPDATE = 'COLLECTION_UPDATE'
export const COLLECTION_UPDATE_SIZE = 'COLLECTION_UPDATE_SIZE'
export const COLLECTION_UPDATE_PAGE = 'COLLECTION_UPDATE_PAGE'
export const COLLECTION_REMOVE_ITEMS = 'COLLECTION_REMOVE_ITEMS'
export const COLLECTION_UPDATE_STATUS_ITEM = 'COLLECTION_UPDATE_STATUS_ITEM'

export const QUESTION_UPDATE = 'QUESTION_UPDATE'
export const QUESTION_UPDATE_SIZE = 'QUESTION_UPDATE_SIZE'
export const QUESTION_UPDATE_PAGE = 'QUESTION_UPDATE_PAGE'
export const QUESTION_REMOVE_ITEMS = 'QUESTION_REMOVE_ITEMS'

export const TAG_UPDATE = 'TAG_UPDATE'
export const TAG_UPDATE_SIZE = 'TAG_UPDATE_SIZE'
export const TAG_UPDATE_PAGE = 'TAG_UPDATE_PAGE'
export const TAG_REMOVE_ITEMS = 'TAG_REMOVE_ITEMS'

export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE'
export const ACCOUNT_UPDATE_SIZE = 'ACCOUNT_UPDATE_SIZE'
export const ACCOUNT_UPDATE_PAGE = 'ACCOUNT_UPDATE_PAGE'

export const ANSWER_UPDATE = 'ANSWER_UPDATE'
export const ANSWER_UPDATE_SIZE = 'ANSWER_UPDATE_SIZE'
export const ANSWER_UPDATE_PAGE = 'ANSWER_UPDATE_PAGE'
export const ANSWER_REMOVE_ITEMS = 'ANSWER_REMOVE_ITEMS'

export default {
  USER_UPDATE,
  USER_RESET,

  COLLECTION_UPDATE,
  COLLECTION_UPDATE_SIZE,
  COLLECTION_UPDATE_PAGE,
  COLLECTION_REMOVE_ITEMS,
  COLLECTION_UPDATE_STATUS_ITEM,

  QUESTION_UPDATE,
  QUESTION_UPDATE_SIZE,
  QUESTION_UPDATE_PAGE,
  QUESTION_REMOVE_ITEMS,

  TAG_UPDATE,
  TAG_UPDATE_SIZE,
  TAG_UPDATE_PAGE,
  TAG_REMOVE_ITEMS,

  ACCOUNT_UPDATE,
  ACCOUNT_UPDATE_SIZE,
  ACCOUNT_UPDATE_PAGE,

  ANSWER_UPDATE,
  ANSWER_UPDATE_SIZE,
  ANSWER_UPDATE_PAGE,
  ANSWER_REMOVE_ITEMS
}
